/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/accounts/accept-invite/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["accounts_accept_invite_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/accounts/create-invite/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["accounts_create_invite_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/accounts/invites/{project_id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_invites_list"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/accounts/invites/{project_id}/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_invites_retrieve"]
    put?: never
    post?: never
    delete: operations["accounts_invites_destroy"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/accounts/me/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_me_retrieve"]
    put: operations["accounts_me_update"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations["accounts_me_partial_update"]
    trace?: never
  }
  "/api/v1/accounts/projects/{project_id}/members/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_projects_members_list"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/accounts/projects/{project_id}/members/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_projects_members_retrieve"]
    put: operations["accounts_projects_members_update"]
    post?: never
    delete: operations["accounts_projects_members_destroy"]
    options?: never
    head?: never
    patch: operations["accounts_projects_members_partial_update"]
    trace?: never
  }
  "/api/v1/accounts/projects/{project_id}/teams/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_projects_teams_list"]
    put?: never
    post: operations["accounts_projects_teams_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/accounts/projects/{project_id}/teams/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["accounts_projects_teams_retrieve"]
    put: operations["accounts_projects_teams_update"]
    post?: never
    delete: operations["accounts_projects_teams_destroy"]
    options?: never
    head?: never
    patch: operations["accounts_projects_teams_partial_update"]
    trace?: never
  }
  "/api/v1/auth/login/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Check the credentials and return the REST Token
     *     if the credentials are valid and authenticated.
     *     Calls Django Auth login method to register User ID
     *     in Django session framework
     *
     *     Accept the following POST parameters: username, password
     *     Return the REST Framework Token Object's key. */
    post: operations["auth_login_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/logout/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Calls Django logout method and delete the Token object
     *     assigned to the current User object.
     *
     *     Accepts/Returns nothing. */
    post: operations["auth_logout_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/password/change/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Calls Django Auth SetPasswordForm save method.
     *
     *     Accepts the following POST parameters: new_password1, new_password2
     *     Returns the success/fail message. */
    post: operations["auth_password_change_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/password/reset/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Calls Django Auth PasswordResetForm save method.
     *
     *     Accepts the following POST parameters: email
     *     Returns the success/fail message. */
    post: operations["auth_password_reset_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/password/reset/confirm/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Password reset e-mail link is confirmed, therefore
     *     this resets the user's password.
     *
     *     Accepts the following POST parameters: token, uid,
     *         new_password1, new_password2
     *     Returns the success/fail message. */
    post: operations["auth_password_reset_confirm_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/registration/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["auth_registration_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/registration/resend-email/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["auth_registration_resend_email_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/registration/verify-email/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["auth_registration_verify_email_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/token/refresh/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Takes a refresh type JSON web token and returns an access type JSON web
     *     token if the refresh token is valid. */
    post: operations["auth_token_refresh_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/token/verify/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Takes a token and indicates if it is valid.  This view provides no
     *     information about a token's fitness for a particular use. */
    post: operations["auth_token_verify_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/user/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Reads and updates UserModel fields
     *     Accepts GET, PUT, PATCH methods.
     *
     *     Default accepted fields: username, first_name, last_name
     *     Default display fields: pk, username, email, first_name, last_name
     *     Read-only fields: pk, email
     *
     *     Returns UserModel fields. */
    get: operations["auth_user_retrieve"]
    /** @description Reads and updates UserModel fields
     *     Accepts GET, PUT, PATCH methods.
     *
     *     Default accepted fields: username, first_name, last_name
     *     Default display fields: pk, username, email, first_name, last_name
     *     Read-only fields: pk, email
     *
     *     Returns UserModel fields. */
    put: operations["auth_user_update"]
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description Reads and updates UserModel fields
     *     Accepts GET, PUT, PATCH methods.
     *
     *     Default accepted fields: username, first_name, last_name
     *     Default display fields: pk, username, email, first_name, last_name
     *     Read-only fields: pk, email
     *
     *     Returns UserModel fields. */
    patch: operations["auth_user_partial_update"]
    trace?: never
  }
  "/api/v1/inbox/integration-conversations/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_integration_conversations_list"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/message-create/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["inbox_message_create_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/messages/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_messages_list"]
    put?: never
    post: operations["inbox_messages_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/messages/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_messages_retrieve"]
    put: operations["inbox_messages_update"]
    post?: never
    delete: operations["inbox_messages_destroy"]
    options?: never
    head?: never
    patch: operations["inbox_messages_partial_update"]
    trace?: never
  }
  "/api/v1/inbox/project-api-keys/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_project_api_keys_list"]
    put?: never
    post: operations["inbox_project_api_keys_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/project-api-keys/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_project_api_keys_retrieve"]
    put: operations["inbox_project_api_keys_update"]
    post?: never
    delete: operations["inbox_project_api_keys_destroy"]
    options?: never
    head?: never
    patch: operations["inbox_project_api_keys_partial_update"]
    trace?: never
  }
  "/api/v1/inbox/project-api-keys/{id}/reset_key/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["inbox_project_api_keys_reset_key_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/project-api-keys/{id}/toggle_active/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["inbox_project_api_keys_toggle_active_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/projects/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_projects_list"]
    put?: never
    post: operations["inbox_projects_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/projects/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_projects_retrieve"]
    put: operations["inbox_projects_update"]
    post?: never
    delete: operations["inbox_projects_destroy"]
    options?: never
    head?: never
    patch: operations["inbox_projects_partial_update"]
    trace?: never
  }
  "/api/v1/inbox/projects/{id}/api_keys/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Get all API keys for a specific project */
    get: operations["inbox_projects_api_keys_retrieve"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/projects/{id}/create_api_key/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Create a new API key for a specific project */
    post: operations["inbox_projects_create_api_key_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/tickets/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_tickets_list"]
    put?: never
    post: operations["inbox_tickets_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/inbox/tickets/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["inbox_tickets_retrieve"]
    put: operations["inbox_tickets_update"]
    post?: never
    delete: operations["inbox_tickets_destroy"]
    options?: never
    head?: never
    patch: operations["inbox_tickets_partial_update"]
    trace?: never
  }
  "/api/v1/integrations/integration-types/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["integrations_integration_types_retrieve"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/integrations/integrations/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["integrations_integrations_list"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/integrations/telegram-integrations/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["integrations_telegram_integrations_list"]
    put?: never
    post: operations["integrations_telegram_integrations_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/integrations/telegram-integrations/{id}/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["integrations_telegram_integrations_retrieve"]
    put: operations["integrations_telegram_integrations_update"]
    post?: never
    delete: operations["integrations_telegram_integrations_destroy"]
    options?: never
    head?: never
    patch: operations["integrations_telegram_integrations_partial_update"]
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AcceptInvite: {
      token: string
    }
    AcceptInviteRequest: {
      token: string
      password: string
    }
    /** @enum {unknown} */
    BlankEnum: ""
    Conversation: {
      /** Format: uuid */
      readonly id: string
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
      /** Format: uuid */
      session?: string | null
      status?: components["schemas"]["StatusEnum"]
      priority?: components["schemas"]["PriorityEnum"]
      /** Format: uuid */
      assignee?: string | null
      team?: number | null
      readonly session_name: string
      readonly session_email: string
      readonly last_message: string
    }
    ConversationRequest: {
      /** Format: uuid */
      session?: string | null
      status?: components["schemas"]["StatusEnum"]
      priority?: components["schemas"]["PriorityEnum"]
      /** Format: uuid */
      assignee?: string | null
      team?: number | null
    }
    CurrentMember: {
      /** Format: uuid */
      readonly id: string
      readonly project: components["schemas"]["CurrentProject"]
      role?: components["schemas"]["Role87aEnum"]
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
      /** Format: uuid */
      user: string
      /** Format: uuid */
      created_by?: string | null
    }
    CurrentProject: {
      /** Format: uuid */
      readonly id: string
      name: string
      /** Format: uuid */
      collection?: string | null
      readonly collection_name: string
      use_cache?: boolean
      use_annotation?: boolean
      agent_switch?: boolean
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    CurrentUser: {
      /** Format: uuid */
      readonly id: string
      /** Format: email */
      email: string
      full_name: string
      phone_number?: string | null
      readonly team: components["schemas"]["Team"]
      readonly team_id: number | null
      readonly project_memberships: components["schemas"]["CurrentMember"][]
      is_active?: boolean
      is_staff?: boolean
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    /** @description Serializer for confirming a password reset attempt. */
    CustomPasswordResetConfirmRequest: {
      new_password1: string
      new_password2: string
      uid: string
      token: string
    }
    /** @description Serializer for requesting a password reset e-mail. */
    CustomPasswordResetRequest: {
      /** Format: email */
      email: string
    }
    IntegrationList: {
      readonly id: string
      readonly integration_type: string
      /** Format: uuid */
      project: string
      is_active: boolean
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      updated_at: string
    }
    Invite: {
      readonly id: number
      /** Format: email */
      email: string
      accepted?: boolean
      /** Format: uuid */
      created_by_user?: string | null
      /** Format: uuid */
      user?: string | null
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    InviteCreate: {
      /** Format: email */
      email: string
      /** Format: uuid */
      project?: string | null
      team?: number | null
      role?: components["schemas"]["Role87aEnum"]
    }
    InviteCreateRequest: {
      /** Format: email */
      email: string
      full_name: string
      /** Format: uuid */
      project?: string | null
      team?: number | null
      role?: components["schemas"]["Role87aEnum"]
    }
    /** @description Serializer for JWT authentication. */
    JWT: {
      access: string
      refresh: string
      user: components["schemas"]["UserDetails"]
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    Member: {
      /** Format: uuid */
      readonly id: string
      user: components["schemas"]["User"]
      role?: components["schemas"]["Role87aEnum"]
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
      /** Format: uuid */
      project: string
      /** Format: uuid */
      created_by?: string | null
    }
    MemberUpdate: {
      role?: components["schemas"]["Role87aEnum"]
    }
    MemberUpdateRequest: {
      role?: components["schemas"]["Role87aEnum"]
      team?: number | null
    }
    Message: {
      /** Format: uuid */
      readonly id: string
      content: string
      role?: (components["schemas"]["MessageRoleEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null
      type?: components["schemas"]["TypeEnum"]
      readonly author: components["schemas"]["User"]
      readonly mentioned_users: components["schemas"]["User"][]
      /** Format: date-time */
      readonly created_at: string
      /** Format: uuid */
      conversation: string
      /** Format: uri */
      audio_file?: string | null
      audio_transcript?: string | null
    }
    MessageCreateUpdate: {
      /** Format: uuid */
      readonly id: string
      content: string
      type?: components["schemas"]["TypeEnum"]
      /** Format: uuid */
      author?: string | null
      mentioned_users?: string[]
      /** Format: date-time */
      readonly created_at: string
      /** Format: uuid */
      conversation: string
    }
    MessageCreateUpdateRequest: {
      content: string
      type?: components["schemas"]["TypeEnum"]
      /** Format: uuid */
      author?: string | null
      mentioned_users?: string[]
      /** Format: uuid */
      conversation: string
    }
    /**
     * @description * `CLIENT` - Client
     *     * `OPERATOR` - Operator
     *     * `AGENT` - Agent
     * @enum {string}
     */
    MessageRoleEnum: "CLIENT" | "OPERATOR" | "AGENT"
    /** @enum {unknown} */
    NullEnum: null
    PaginatedConversationList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["Conversation"][]
    }
    PaginatedIntegrationListList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["IntegrationList"][]
    }
    PaginatedInviteList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["Invite"][]
    }
    PaginatedMemberList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["Member"][]
    }
    PaginatedMessageList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["Message"][]
    }
    PaginatedProjectAPIKeyList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["ProjectAPIKey"][]
    }
    PaginatedProjectList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["Project"][]
    }
    PaginatedTeamList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["Team"][]
    }
    PaginatedTelegramIntegrationList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results: components["schemas"]["TelegramIntegration"][]
    }
    PasswordChangeRequest: {
      new_password1: string
      new_password2: string
    }
    PatchedConversationRequest: {
      /** Format: uuid */
      session?: string | null
      status?: components["schemas"]["StatusEnum"]
      priority?: components["schemas"]["PriorityEnum"]
      /** Format: uuid */
      assignee?: string | null
      team?: number | null
    }
    PatchedMemberUpdateRequest: {
      role?: components["schemas"]["Role87aEnum"]
      team?: number | null
    }
    PatchedMessageCreateUpdateRequest: {
      content?: string
      type?: components["schemas"]["TypeEnum"]
      /** Format: uuid */
      author?: string | null
      mentioned_users?: string[]
      /** Format: uuid */
      conversation?: string
    }
    PatchedProjectAPIKeyRequest: {
      name?: string
      /** Format: uuid */
      project?: string
      active?: boolean
      /** Format: date-time */
      expires_at?: string | null
    }
    PatchedProjectRequest: {
      name?: string
      /** Format: uuid */
      collection?: string | null
      use_cache?: boolean
      use_annotation?: boolean
      agent_switch?: boolean
    }
    PatchedTeamCreateRequest: {
      name?: string
      /** Format: binary */
      icon?: string | null
    }
    PatchedTelegramIntegrationRequest: {
      /** Format: uuid */
      project?: string
      bot_api_token?: string
      is_active?: boolean
    }
    PatchedUserUpdateRequest: {
      full_name?: string
    }
    /**
     * @description * `LOW` - Low
     *     * `MEDIUM` - Medium
     *     * `HIGH` - High
     * @enum {string}
     */
    PriorityEnum: "LOW" | "MEDIUM" | "HIGH"
    Project: {
      /** Format: uuid */
      readonly id: string
      name: string
      /** Format: uuid */
      collection?: string | null
      readonly collection_name: string
      use_cache?: boolean
      use_annotation?: boolean
      agent_switch?: boolean
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    ProjectAPIKey: {
      /** Format: uuid */
      readonly id: string
      name: string
      /** Format: uuid */
      project: string
      readonly project_name: string
      readonly key: string
      active?: boolean
      /** Format: date-time */
      expires_at?: string | null
      readonly request_count: number
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    ProjectAPIKeyCreate: {
      name: string
      /** Format: uuid */
      project: string
      active?: boolean
      /** Format: date-time */
      expires_at?: string | null
    }
    ProjectAPIKeyCreateRequest: {
      name: string
      /** Format: uuid */
      project: string
      active?: boolean
      /** Format: date-time */
      expires_at?: string | null
    }
    ProjectAPIKeyRequest: {
      name: string
      /** Format: uuid */
      project: string
      active?: boolean
      /** Format: date-time */
      expires_at?: string | null
    }
    ProjectCreate: {
      name: string
      use_cache?: boolean
      use_annotation?: boolean
    }
    ProjectCreateRequest: {
      name: string
      use_cache?: boolean
      use_annotation?: boolean
    }
    ProjectRequest: {
      name: string
      /** Format: uuid */
      collection?: string | null
      use_cache?: boolean
      use_annotation?: boolean
      agent_switch?: boolean
    }
    RegisterRequest: {
      /** Format: email */
      email: string
      full_name: string
      password: string
    }
    ResendEmailVerificationRequest: {
      /** Format: email */
      email: string
    }
    RestAuthDetail: {
      readonly detail: string
    }
    /**
     * @description * `ADMIN` - Admin
     *     * `MEMBER` - Member
     * @enum {string}
     */
    Role87aEnum: "ADMIN" | "MEMBER"
    /**
     * @description * `OPEN` - Open
     *     * `CLOSED` - Closed
     * @enum {string}
     */
    StatusEnum: "OPEN" | "CLOSED"
    Team: {
      readonly id: number
      name: string
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
      /** Format: uri */
      icon?: string | null
      readonly icon_url: string
      readonly project_name: string
      readonly members_count: string
    }
    TeamCreate: {
      name: string
      /** Format: uri */
      icon?: string | null
    }
    TeamCreateRequest: {
      name: string
      /** Format: binary */
      icon?: string | null
    }
    TelegramIntegration: {
      /** Format: uuid */
      readonly id: string
      /** Format: uuid */
      project: string
      bot_api_token: string
      is_active?: boolean
    }
    TelegramIntegrationRequest: {
      /** Format: uuid */
      project: string
      bot_api_token: string
      is_active?: boolean
    }
    TokenRefresh: {
      readonly access: string
    }
    TokenRefreshRequest: {
      refresh: string
    }
    TokenVerifyRequest: {
      token: string
    }
    /**
     * @description * `MESSAGE` - Message
     *     * `NOTE` - Note
     *     * `AUDIO` - Audio
     * @enum {string}
     */
    TypeEnum: "MESSAGE" | "NOTE" | "AUDIO"
    User: {
      /** Format: uuid */
      readonly id: string
      /** Format: email */
      email: string
      full_name: string
      phone_number?: string | null
      readonly team: components["schemas"]["Team"]
      is_active?: boolean
      is_staff?: boolean
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    /** @description User model w/o password */
    UserDetails: {
      /**
       * Id
       * Format: uuid
       */
      readonly pk: string
      /** Format: email */
      readonly email: string
    }
    UserUpdate: {
      /** Format: uuid */
      readonly id: string
      full_name: string
    }
    UserUpdateRequest: {
      full_name: string
    }
    VerifyEmailRequest: {
      key: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  accounts_accept_invite_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInviteRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["AcceptInviteRequest"]
        "multipart/form-data": components["schemas"]["AcceptInviteRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AcceptInvite"]
        }
      }
    }
  }
  accounts_create_invite_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteCreateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["InviteCreateRequest"]
        "multipart/form-data": components["schemas"]["InviteCreateRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InviteCreate"]
        }
      }
    }
  }
  accounts_invites_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedInviteList"]
        }
      }
    }
  }
  accounts_invites_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this invite model. */
        id: number
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Invite"]
        }
      }
    }
  }
  accounts_invites_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this invite model. */
        id: number
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  accounts_me_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CurrentUser"]
        }
      }
    }
  }
  accounts_me_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["UserUpdateRequest"]
        "multipart/form-data": components["schemas"]["UserUpdateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserUpdate"]
        }
      }
    }
  }
  accounts_me_partial_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUserUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"]
        "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserUpdate"]
        }
      }
    }
  }
  accounts_projects_members_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedMemberList"]
        }
      }
    }
  }
  accounts_projects_members_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Member"]
        }
      }
    }
  }
  accounts_projects_members_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
        project_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["MemberUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["MemberUpdateRequest"]
        "multipart/form-data": components["schemas"]["MemberUpdateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MemberUpdate"]
        }
      }
    }
  }
  accounts_projects_members_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  accounts_projects_members_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
        project_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedMemberUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedMemberUpdateRequest"]
        "multipart/form-data": components["schemas"]["PatchedMemberUpdateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MemberUpdate"]
        }
      }
    }
  }
  accounts_projects_teams_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedTeamList"]
        }
      }
    }
  }
  accounts_projects_teams_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamCreateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["TeamCreateRequest"]
        "multipart/form-data": components["schemas"]["TeamCreateRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TeamCreate"]
        }
      }
    }
  }
  accounts_projects_teams_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this team. */
        id: number
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Team"]
        }
      }
    }
  }
  accounts_projects_teams_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this team. */
        id: number
        project_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamCreateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["TeamCreateRequest"]
        "multipart/form-data": components["schemas"]["TeamCreateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TeamCreate"]
        }
      }
    }
  }
  accounts_projects_teams_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this team. */
        id: number
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  accounts_projects_teams_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this team. */
        id: number
        project_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedTeamCreateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedTeamCreateRequest"]
        "multipart/form-data": components["schemas"]["PatchedTeamCreateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TeamCreate"]
        }
      }
    }
  }
  auth_login_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"]
        "multipart/form-data": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["JWT"]
        }
      }
    }
  }
  auth_logout_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_password_change_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChangeRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"]
        "multipart/form-data": components["schemas"]["PasswordChangeRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_password_reset_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomPasswordResetRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["CustomPasswordResetRequest"]
        "multipart/form-data": components["schemas"]["CustomPasswordResetRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_password_reset_confirm_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomPasswordResetConfirmRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["CustomPasswordResetConfirmRequest"]
        "multipart/form-data": components["schemas"]["CustomPasswordResetConfirmRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_registration_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"]
        "multipart/form-data": components["schemas"]["RegisterRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_registration_resend_email_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendEmailVerificationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ResendEmailVerificationRequest"]
        "multipart/form-data": components["schemas"]["ResendEmailVerificationRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_registration_verify_email_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["VerifyEmailRequest"]
        "multipart/form-data": components["schemas"]["VerifyEmailRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RestAuthDetail"]
        }
      }
    }
  }
  auth_token_refresh_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefreshRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"]
        "multipart/form-data": components["schemas"]["TokenRefreshRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TokenRefresh"]
        }
      }
    }
  }
  auth_token_verify_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenVerifyRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"]
        "multipart/form-data": components["schemas"]["TokenVerifyRequest"]
      }
    }
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  auth_user_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserDetails"]
        }
      }
    }
  }
  auth_user_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserDetails"]
        }
      }
    }
  }
  auth_user_partial_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserDetails"]
        }
      }
    }
  }
  inbox_integration_conversations_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedConversationList"]
        }
      }
    }
  }
  inbox_message_create_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageCreateUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["MessageCreateUpdateRequest"]
        "multipart/form-data": components["schemas"]["MessageCreateUpdateRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageCreateUpdate"]
        }
      }
    }
  }
  inbox_messages_list: {
    parameters: {
      query?: {
        conversation?: string
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
        /** @description Which field to use when ordering the results. */
        ordering?: string
        /** @description A search term. */
        search?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedMessageList"]
        }
      }
    }
  }
  inbox_messages_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageCreateUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["MessageCreateUpdateRequest"]
        "multipart/form-data": components["schemas"]["MessageCreateUpdateRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageCreateUpdate"]
        }
      }
    }
  }
  inbox_messages_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Message"]
        }
      }
    }
  }
  inbox_messages_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageCreateUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["MessageCreateUpdateRequest"]
        "multipart/form-data": components["schemas"]["MessageCreateUpdateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageCreateUpdate"]
        }
      }
    }
  }
  inbox_messages_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  inbox_messages_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedMessageCreateUpdateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedMessageCreateUpdateRequest"]
        "multipart/form-data": components["schemas"]["PatchedMessageCreateUpdateRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageCreateUpdate"]
        }
      }
    }
  }
  inbox_project_api_keys_list: {
    parameters: {
      query?: {
        active?: boolean
        /** @description Number of results to return per page. */
        limit?: number
        name?: string
        /** @description The initial index from which to return the results. */
        offset?: number
        /** @description Which field to use when ordering the results. */
        ordering?: string
        project?: string
        /** @description A search term. */
        search?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedProjectAPIKeyList"]
        }
      }
    }
  }
  inbox_project_api_keys_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectAPIKeyCreateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectAPIKeyCreateRequest"]
        "multipart/form-data": components["schemas"]["ProjectAPIKeyCreateRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectAPIKeyCreate"]
        }
      }
    }
  }
  inbox_project_api_keys_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project api key. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectAPIKey"]
        }
      }
    }
  }
  inbox_project_api_keys_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project api key. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectAPIKeyRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectAPIKeyRequest"]
        "multipart/form-data": components["schemas"]["ProjectAPIKeyRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectAPIKey"]
        }
      }
    }
  }
  inbox_project_api_keys_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project api key. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  inbox_project_api_keys_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project api key. */
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProjectAPIKeyRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectAPIKeyRequest"]
        "multipart/form-data": components["schemas"]["PatchedProjectAPIKeyRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectAPIKey"]
        }
      }
    }
  }
  inbox_project_api_keys_reset_key_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project api key. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectAPIKeyRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectAPIKeyRequest"]
        "multipart/form-data": components["schemas"]["ProjectAPIKeyRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectAPIKey"]
        }
      }
    }
  }
  inbox_project_api_keys_toggle_active_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project api key. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectAPIKeyRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectAPIKeyRequest"]
        "multipart/form-data": components["schemas"]["ProjectAPIKeyRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectAPIKey"]
        }
      }
    }
  }
  inbox_projects_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        name?: string
        /** @description The initial index from which to return the results. */
        offset?: number
        /** @description Which field to use when ordering the results. */
        ordering?: string
        /** @description A search term. */
        search?: string
        use_annotation?: boolean
        use_cache?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedProjectList"]
        }
      }
    }
  }
  inbox_projects_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreateRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectCreateRequest"]
        "multipart/form-data": components["schemas"]["ProjectCreateRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProjectCreate"]
        }
      }
    }
  }
  inbox_projects_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Project"]
        }
      }
    }
  }
  inbox_projects_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectRequest"]
        "multipart/form-data": components["schemas"]["ProjectRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Project"]
        }
      }
    }
  }
  inbox_projects_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  inbox_projects_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project. */
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProjectRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectRequest"]
        "multipart/form-data": components["schemas"]["PatchedProjectRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Project"]
        }
      }
    }
  }
  inbox_projects_api_keys_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Project"]
        }
      }
    }
  }
  inbox_projects_create_api_key_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this project. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ProjectRequest"]
        "multipart/form-data": components["schemas"]["ProjectRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Project"]
        }
      }
    }
  }
  inbox_tickets_list: {
    parameters: {
      query?: {
        assignee?: string
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
        /** @description Which field to use when ordering the results. */
        ordering?: string
        priority?: string
        /** @description A search term. */
        search?: string
        session__project?: string
        status?: string
        team?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedConversationList"]
        }
      }
    }
  }
  inbox_tickets_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConversationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ConversationRequest"]
        "multipart/form-data": components["schemas"]["ConversationRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conversation"]
        }
      }
    }
  }
  inbox_tickets_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this conversation. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conversation"]
        }
      }
    }
  }
  inbox_tickets_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this conversation. */
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConversationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["ConversationRequest"]
        "multipart/form-data": components["schemas"]["ConversationRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conversation"]
        }
      }
    }
  }
  inbox_tickets_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this conversation. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  inbox_tickets_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this conversation. */
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedConversationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedConversationRequest"]
        "multipart/form-data": components["schemas"]["PatchedConversationRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Conversation"]
        }
      }
    }
  }
  integrations_integration_types_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  integrations_integrations_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedIntegrationListList"]
        }
      }
    }
  }
  integrations_telegram_integrations_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedTelegramIntegrationList"]
        }
      }
    }
  }
  integrations_telegram_integrations_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TelegramIntegrationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["TelegramIntegrationRequest"]
        "multipart/form-data": components["schemas"]["TelegramIntegrationRequest"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TelegramIntegration"]
        }
      }
    }
  }
  integrations_telegram_integrations_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this telegram integration. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TelegramIntegration"]
        }
      }
    }
  }
  integrations_telegram_integrations_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this telegram integration. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TelegramIntegrationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["TelegramIntegrationRequest"]
        "multipart/form-data": components["schemas"]["TelegramIntegrationRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TelegramIntegration"]
        }
      }
    }
  }
  integrations_telegram_integrations_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this telegram integration. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  integrations_telegram_integrations_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A UUID string identifying this telegram integration. */
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedTelegramIntegrationRequest"]
        "application/x-www-form-urlencoded": components["schemas"]["PatchedTelegramIntegrationRequest"]
        "multipart/form-data": components["schemas"]["PatchedTelegramIntegrationRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TelegramIntegration"]
        }
      }
    }
  }
}
